[package]
name = "tinymist-l10n"
description = "Localization support for tinymist and typst."
categories = ["compilers", "command-line-utilities"]
keywords = ["language", "typst"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "tinymist-l10n"
path = "src/main.rs"
required-features = ["cli"]
test = false
doctest = false
bench = false
doc = false

[dependencies]

anyhow.workspace = true
clap = { workspace = true, optional = true }
ecow.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
serde_json.workspace = true
walkdir.workspace = true

[dev-dependencies]
insta.workspace = true

[features]
default = ["cli"]
cli = ["clap", "clap/wrap_help"]

[lints]
workspace = true
