name: Bug report
description: File a bug/issue
labels: ["bug", "need-to-investigate"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Platform
    description: Which platform are you on?
    options: 
      - x64 Windows (win32-x64, Most Common)
      - x64 Linux (linux-x64, Most Common)
      - Apple Silicon macOS (darwin-arm64, Most Common)
      - ARM64 Windows (win32-arm64)
      - ARM64 Linux (linux-arm64)
      - ARMv7 Linux (linux-armhf)
      - Intel macOS (darwin-x64)
      - x64 Alpine Linux (alpine-x64)
      - ARM64 Alpine Linux (alpine-arm64)
      - Browser (web)
      - Other Platforms (universal)
  validations:
    required: true
- type: dropdown
  attributes:
    label: Editor
    description: Which editor are you using?
    options:
      - VS Cod(e,ium)
      - Neovim
      - Emacs
      - Sublime Text
      - Helix
      - Zed
      - CLI (Command Line Interface)
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: Editor Version
    description: |
     For example, for VSCode, get the version in (Help -> About)
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    render: md
  validations:
    required: true
- type: textarea
  attributes:
    label: Server Logs
    description: |
      For example, for VSCode, get the logs in (Output Panel -> Tinymist).
      Please don't truncate it for us, attach it as a file if it's too long.
  validations:
    required: true
- type: textarea
  attributes:
    label: Browser Logs
    description: |
      For example, for VSCode, get the logs in (Help -> Toggle Developer Tools -> Console).
      Please don't truncate it for us, attach it as a file if it's too long.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    render: md
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false