name: Feature request
description: Create a feature request
labels: ["enhancement", "need-to-investigate"]
body:
- type: textarea
  attributes:
    label: Motivation
    description: |
      A brief use case, scenario, or other argument used in support of this *feature*.
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: |
      A clear and concise description of this *feature*.
  validations:
    required: false
- type: textarea
  attributes:
    label: More Examples/Questions
    description: |
      - Using examples to profile how you imagine the *feature* should be
      - Raising questions to highlight the uncertain design for the *feature*.
  validations:
    required: false
