[package]
name = "tinymist-wasm"
description.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Minimal dependencies for WASM
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = ["console"] }
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }

# Core tinymist dependencies for basic language features
lsp-types = { workspace = true }
typst = { workspace = true }
typst-shim = { workspace = true }
tinymist-query = { workspace = true }
tinymist-world = { workspace = true, default-features = false }
tinymist-project = { workspace = true, default-features = false }
ecow = { workspace = true }

[features]
default = []

# We don't need the patch section as it's being ignored for non-root packages
# The workspace's patch will be used instead

[lints]
workspace = true
