[package]
name = "sync-lsp"
description = "Sync LSP server inspired by async-lsp, primarily for tinymist."
categories = ["compilers"]
keywords = ["lsp", "language", "language-server"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

anyhow.workspace = true
clap = { workspace = true, optional = true }
crossbeam-channel.workspace = true
futures.workspace = true
log.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
parking_lot.workspace = true
reflexo.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
