[package]
name = "tinymist-preview"
description = "A previewer for the Typst typesetting system."
license = "MIT"
repository = "https://github.com/Enter-tainer/typst-preview"
version.workspace = true
authors = ["The Typst Project Developers"]
edition.workspace = true
keywords = ["typst"]
include = ["src/**/*", "/LICENSE", "/README.md"]
rust-version.workspace = true

[dependencies]

bytes.workspace = true
comemo.workspace = true
env_logger.workspace = true
futures.workspace = true
indexmap.workspace = true
log.workspace = true
parking_lot.workspace = true
reflexo-vec2svg.workspace = true
reflexo-typst.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
typst.workspace = true
tinymist-assets.workspace = true
tinymist-std.workspace = true
typst-macros.workspace = true
typst-timing.workspace = true
typst-assets.workspace = true

clap = { workspace = true, optional = true }

[features]

default = ["no-content-hint"]

# Disable the default content hint.
# This requires modifying typst.
no-content-hint = ["reflexo-typst/no-content-hint"]

[lints]
workspace = true
