[package]
name = "typst-preview"
description = "A previewer for the Typst typesetting system."
license = "MIT"
repository = "https://github.com/Enter-tainer/typst-preview"
version = "0.11.7"
authors = ["The Typst Project Developers"]
edition = "2021"
build = "build.rs"
keywords = ["typst"]
include = ["src/**/*", "/LICENSE", "/README.md", "build.rs"]

[[bin]]
name = "typst-preview"
required-features = ["cli"]
path = "src/main.rs"
test = false
doctest = false
bench = false
doc = false

[dependencies]
typst = "0.11.1"
typst-assets = { version = "0.11.1", features = ["fonts"] }
typst-ts-svg-exporter = { version = "0.5.0-rc4" }
typst-ts-core = { version = "0.5.0-rc4", default-features = false, features = [
  "flat-vector",
  "vector-bbox",
] }
typst-ts-compiler = { version = "0.5.0-rc4", optional = true }
comemo = "0.4"
elsa = "1.10"
memmap2 = "0.9.4"
notify = "6"
once_cell = "1"
tokio = { version = "1.37.0", features = ["full"] }
tokio-tungstenite = "0.21.0"
tiny-skia = "0.11"
env_logger = "0.11.3"
log = "0.4.21"
serde_json = "1.0.117"
futures = "0.3.30"
indexmap = "2"
serde = "1.0.202"
await-tree = "0.1.2"

clap = { version = "4.5.4", features = ["derive", "env"], optional = true }
open = { version = "5.1.3", optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
[patch.crates-io]

# typst = { path = "../../../typst/crates/typst" }
# typst-syntax = { path = "../../../typst/crates/typst-syntax" }
# hayagriva = { path = "../../rust/hayagriva" }
# typst-ts-svg-exporter = { path = "../../exporter/svg" }
# typst-ts-compiler = { path = "../../compiler" }
# typst-ts-core = { path = "../../core" }

[build-dependencies]
clap = { version = "4.5.4", features = ["derive", "string"] }
clap_complete = "4.5.2"
clap_mangen = "0.2.20"
vergen = { version = "8.3.1", features = [
  "build",
  "cargo",
  "git",
  "git2",
  "rustc",
] }
anyhow = "1.0.83"

[features]

default = ["embed-fonts", "cli"]

# Embeds Typst's default fonts for
# - text (Linux Libertine),
# - math (New Computer Modern Math), and
# - code (Deja Vu Sans Mono)
# and additionally New Computer Modern for text
# into the binary.
embed-fonts = ["typst-assets/fonts"]
# Disable the default content hint.
# This requires modifying typst.
no-content-hint = ["typst-ts-core/no-content-hint"]

embed-html = []

cli = [
  "hyper",
  "clap",
  "open",
  "typst-ts-compiler",
  "no-content-hint",
  # "embed-html",
]

[profile.release]
debug = true
