[package]
name = "typst-preview"
description = "A previewer for the Typst typesetting system."
license = "MIT"
repository = "https://github.com/Enter-tainer/typst-preview"
version.workspace = true
authors = ["The Typst Project Developers"]
edition.workspace = true
keywords = ["typst"]
include = ["src/**/*", "/LICENSE", "/README.md"]

[dependencies]
typst.workspace = true
tinymist-assets.workspace = true
typst-assets.workspace = true
comemo.workspace = true

typst-ts-svg-exporter.workspace = true
typst-ts-core = { workspace = true, default-features = false, features = [
  "flat-vector",
  "vector-bbox",
] }
typst-ts-compiler.workspace = true
once_cell.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
env_logger.workspace = true
log.workspace = true
serde_json.workspace = true
futures.workspace = true
indexmap.workspace = true
serde.workspace = true
await-tree.workspace = true

clap = { workspace = true, optional = true }

[features]

default = ["no-content-hint"]

# Disable the default content hint.
# This requires modifying typst.
no-content-hint = ["typst-ts-core/no-content-hint"]
