// The toml looks like that:
// # The translation are partially generated by copilot

// [description]
// en = "An integrated language service for Typst"
// zh-CN = "Typst 的集成语言服务"

import * as fs from "fs";
import * as path from "path";

const __dirname = new URL(".", import.meta.url).toString().replace("file:///", "");
const projectRoot = path.resolve(__dirname, "..");

function translate(input, output) {
  const data = fs.readFileSync(path.resolve(projectRoot, input), "utf-8");
  const lines = data
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => !line.startsWith("#") && line.length > 0);

  const translations = {};
  let key = "";
  for (let line of lines) {
    if (line.startsWith("[")) {
      key = line.substring(1, line.length - 1);
    } else {
      const equalIndex = line.indexOf("=");
      const lang = line.substring(0, equalIndex).trim();
      const value = line.substring(equalIndex + 1).trim();

      translations[lang] ||= {};
      translations[lang][key] = JSON.parse(value);
    }
  }

  const langs = Object.keys(translations);
  const langEn = langs.find((lang) => lang === "en");
  if (!langEn) {
    console.error("en is required");
    return;
  }

  const langRest = langs.filter((lang) => lang !== "en");

  const langEnPath = path.resolve(projectRoot, `${output}/package.nls.json`);
  const langEnData = translations["en"];
  fs.writeFileSync(langEnPath, JSON.stringify(langEnData, null, 2));

  for (let lang of langRest) {
    const langPath = path.resolve(projectRoot, `${output}/package.nls.${lang}.json`);
    const langData = translations[lang];
    fs.writeFileSync(langPath, JSON.stringify(langData, null, 2));
  }

  return translations;
}

function genVscodeExt() {
  const translations = translate("locales/tinymist-vscode.toml", "editors/vscode");

  const pat = /\%(extension\.tinymist\..*?)\%/g;
  const data = fs.readFileSync(path.resolve(projectRoot, "editors/vscode/package.json"), "utf-8");
  const matchAll = data.matchAll(pat);
  const used = Array.from(matchAll).map((m) => m[1]);
  used.push("description");

  const en = translations["en"];
  const enKeys = Object.keys(en);
  const missing = used.filter((key) => !enKeys.includes(key));
  if (missing.length > 0) {
    console.error("Missing translations", missing);
  }
  const extra = enKeys.filter((key) => !used.includes(key));
  if (extra.length > 0) {
    console.error("Extra translations", extra);
  }

  return translations;
}

export const vscodeExtTranslations = genVscodeExt();
